In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
merge1 = pd.read_csv("merge1.csv", encoding='utf-8-sig')
merge2 = pd.read_csv("merge2.csv", encoding='utf-8-sig')
merge3 = pd.read_csv("merge3.csv", encoding='utf-8-sig')

In [4]:
merge1

,Unnamed: 0,Unnamed: 0.1,base_date,emd_nm,em_g,korean_resd_pop_cnt,korean_work_pop_cnt,korean_visit_pop_cnt,longtermfrgn_기타_visit_pop_cnt,longtermfrgn_아시아_visit_pop_cnt,...,농축수산물_cnt,마트/슈퍼마켓_cnt,배달_cnt,식품_cnt,아시아음식_cnt,양식_cnt,주점및주류판매_cnt,패스트푸드_cnt,한식_cnt,부페_cnt
0,0,0,2021-07-01,아라동,4345753.50,1034529.75,105873.875,279090.780,182.803770,5017.3467,...,392.702800,2936.33280,805.672400,717.36100,197.809420,95.010510,56.301266,557.634900,2306.11870,5.164090
1,1,1,2021-07-02,아라동,3902727.50,1036852.40,81649.150,276916.000,166.711260,4692.2290,...,371.246730,2856.85470,999.765400,752.15390,210.186980,144.916660,49.916030,617.561770,2494.87400,0.688263
2,2,2,2021-07-03,아라동,4352217.50,1031199.40,51740.050,249012.550,123.049510,4158.7880,...,384.542880,2871.37060,959.425800,791.68880,236.064540,132.605420,59.530014,564.938350,2445.84900,-0.591933
3,3,3,2021-07-04,아라동,4399642.00,1061944.80,53604.110,232245.640,83.948494,3776.0117,...,289.681000,2551.97950,885.660900,643.06976,173.633270,74.253624,41.481243,474.924070,1936.82340,0.023438
4,4,4,2021-07-05,아라동,4547476.00,1026342.70,116858.590,271028.880,132.989180,3706.3580,...,300.356230,2454.81840,656.408100,720.97626,130.798190,75.342255,32.881523,354.145750,2216.90840,5.065386
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,57,57,2021-08-27,표선면,853743.75,224344.10,20565.379,91842.530,77.611626,2863.4912,...,41.989662,425.29270,51.266590,258.30720,48.630230,24.950994,6.876611,94.862240,387.01852,0.061321
740,58,58,2021-08-28,표선면,743999.00,224664.31,17048.488,108561.550,81.837140,3004.5981,...,48.569690,409.53824,49.164560,249.03181,51.543560,19.948305,14.465944,104.913870,378.75640,0.382955
741,59,59,2021-08-29,표선면,748922.40,232826.64,14881.126,102178.555,156.736070,2355.5996,...,30.513824,348.29922,60.358624,206.56460,49.353462,12.704640,4.060434,68.219826,351.56888,0.712225
742,60,60,2021-08-30,표선면,768014.40,226489.64,20379.592,88106.016,117.704240,2529.0444,...,45.619633,386.37204,38.257930,250.74019,35.225857,5.785948,13.422240,81.268810,337.23270,0.239685
743,61,61,2021-08-31,표선면,792626.90,222701.88,22297.447,92477.070,74.850720,2744.2212,...,39.411114,409.02084,30.701977,254.88278,47.286330,12.026168,6.898519,75.281890,386.37030,-0.027216

In [7]:
merge1 = merge1.drop(['Unnamed: 0', 'Unnamed: 0.1'], axis=1)

In [8]:
merge1

,base_date,emd_nm,em_g,korean_resd_pop_cnt,korean_work_pop_cnt,korean_visit_pop_cnt,longtermfrgn_기타_visit_pop_cnt,longtermfrgn_아시아_visit_pop_cnt,longtermfrgn_기타_resd_pop_cnt,longtermfrgn_아시아_resd_pop_cnt,...,농축수산물_cnt,마트/슈퍼마켓_cnt,배달_cnt,식품_cnt,아시아음식_cnt,양식_cnt,주점및주류판매_cnt,패스트푸드_cnt,한식_cnt,부페_cnt
0,2021-07-01,아라동,4345753.50,1034529.75,105873.875,279090.780,182.803770,5017.3467,1213.11060,24995.6760,...,392.702800,2936.33280,805.672400,717.36100,197.809420,95.010510,56.301266,557.634900,2306.11870,5.164090
1,2021-07-02,아라동,3902727.50,1036852.40,81649.150,276916.000,166.711260,4692.2290,1211.11430,25075.2830,...,371.246730,2856.85470,999.765400,752.15390,210.186980,144.916660,49.916030,617.561770,2494.87400,0.688263
2,2021-07-03,아라동,4352217.50,1031199.40,51740.050,249012.550,123.049510,4158.7880,1138.47080,25092.4300,...,384.542880,2871.37060,959.425800,791.68880,236.064540,132.605420,59.530014,564.938350,2445.84900,-0.591933
3,2021-07-04,아라동,4399642.00,1061944.80,53604.110,232245.640,83.948494,3776.0117,1111.87080,25392.1450,...,289.681000,2551.97950,885.660900,643.06976,173.633270,74.253624,41.481243,474.924070,1936.82340,0.023438
4,2021-07-05,아라동,4547476.00,1026342.70,116858.590,271028.880,132.989180,3706.3580,1250.21460,25964.8900,...,300.356230,2454.81840,656.408100,720.97626,130.798190,75.342255,32.881523,354.145750,2216.90840,5.065386
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,2021-08-27,표선면,853743.75,224344.10,20565.379,91842.530,77.611626,2863.4912,199.50511,7394.9360,...,41.989662,425.29270,51.266590,258.30720,48.630230,24.950994,6.876611,94.862240,387.01852,0.061321
740,2021-08-28,표선면,743999.00,224664.31,17048.488,108561.550,81.837140,3004.5981,188.70505,7458.6294,...,48.569690,409.53824,49.164560,249.03181,51.543560,19.948305,14.465944,104.913870,378.75640,0.382955
741,2021-08-29,표선면,748922.40,232826.64,14881.126,102178.555,156.736070,2355.5996,222.16866,7590.1620,...,30.513824,348.29922,60.358624,206.56460,49.353462,12.704640,4.060434,68.219826,351.56888,0.712225
742,2021-08-30,표선면,768014.40,226489.64,20379.592,88106.016,117.704240,2529.0444,196.45059,7184.5810,...,45.619633,386.37204,38.257930,250.74019,35.225857,5.785948,13.422240,81.268810,337.23270,0.239685
743,2021-08-31,표선면,792626.90,222701.88,22297.447,92477.070,74.850720,2744.2212,184.41054,7029.2505,...,39.411114,409.02084,30.701977,254.88278,47.286330,12.026168,6.898519,75.281890,386.37030,-0.027216

In [9]:
merge2

,base_date,emd_nm,em_g,korean_resd_pop_cnt,korean_work_pop_cnt,korean_visit_pop_cnt,longtermfrgn_기타_visit_pop_cnt,longtermfrgn_아시아_visit_pop_cnt,longtermfrgn_기타_resd_pop_cnt,longtermfrgn_아시아_resd_pop_cnt,...,농축수산물_cnt,마트/슈퍼마켓_cnt,배달_cnt,식품_cnt,아시아음식_cnt,양식_cnt,주점및주류판매_cnt,패스트푸드_cnt,한식_cnt,부페_cnt
0,2021-07-01,한림읍,1831115.00,464196.10,41969.5700,154112.470,171.789580,12453.9990,584.355600,24560.5060,...,53.953180,632.08020,128.591320,531.409900,74.435310,25.160667,4.761936,149.733600,805.99750,0.864450
1,2021-07-02,한림읍,1884890.60,463454.20,43223.3050,155726.730,160.225630,12492.9550,597.454400,24685.3730,...,59.289925,639.79320,129.253950,528.167540,80.510826,28.354500,6.338808,156.260640,829.53360,0.745799
2,2021-07-03,한림읍,1936671.20,462779.40,41797.1370,160414.310,155.714830,12254.8030,593.911300,24442.6110,...,65.952280,659.55250,138.224640,533.566600,89.739010,32.619564,7.957044,167.322780,844.26227,0.560709
3,2021-07-04,한림읍,1956651.80,461076.94,37399.4180,164332.660,151.262830,11633.8480,575.429440,23623.4500,...,69.921165,683.85680,149.262160,542.828500,99.531400,36.384438,9.276405,176.442580,847.01984,0.351221
4,2021-07-05,한림읍,1927912.90,459470.62,32726.5300,162530.800,148.911830,10585.1440,550.144300,22681.7680,...,70.246540,696.11510,154.154300,552.127100,103.374890,37.028100,9.906166,176.207200,822.33215,0.120131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987,2021-08-27,봉개동,449354.88,90951.72,24708.6110,100565.945,54.418630,2456.7646,67.685970,1257.3971,...,36.908707,204.56510,31.378540,78.584580,32.140140,16.946415,2.982866,45.843890,293.15268,0.932526
988,2021-08-28,봉개동,455262.25,95218.03,12464.5010,98911.710,48.182285,2769.3188,58.677597,1276.5323,...,33.973686,266.81060,35.505074,90.891846,37.858524,10.208511,5.418940,46.823956,343.22446,-0.033071
989,2021-08-29,봉개동,577467.56,103318.70,8064.1846,83353.310,29.271873,2087.7590,57.892890,1534.6708,...,18.084908,262.73758,34.329163,47.758186,21.507116,14.482290,3.272454,54.223980,238.10564,0.632160
990,2021-08-30,봉개동,532807.00,94296.19,24215.6020,91574.680,47.102478,1870.3562,57.766155,1455.2350,...,32.355297,238.47687,17.284134,77.256775,12.893355,3.797415,1.952292,32.441063,275.70483,0.592513
991,2021-08-31,봉개동,477967.88,92158.92,27862.7900,93602.340,46.212154,2301.4130,46.699350,1277.6127,...,29.062010,229.12363,18.939678,80.975050,20.124195,5.958984,3.407233,44.592457,268.08948,-0.105569

In [10]:
merge3

,Unnamed: 0,base_date,emd_nm,em_g,korean_resd_pop_cnt,korean_work_pop_cnt,korean_visit_pop_cnt,longtermfrgn_기타_visit_pop_cnt,longtermfrgn_아시아_visit_pop_cnt,longtermfrgn_기타_resd_pop_cnt,...,농축수산물_cnt,마트/슈퍼마켓_cnt,배달_cnt,식품_cnt,아시아음식_cnt,양식_cnt,주점및주류판매_cnt,패스트푸드_cnt,한식_cnt,부페_cnt
0,0,2021-07-01,대륜동,1157136.000,334651.84,30443.098,153682.67,268.03230,2446.2905,145.62045,...,38.646618,762.059100,183.366910,248.291930,54.293083,38.920235,8.797337,166.063020,661.628800,-0.206447
1,1,2021-07-02,대륜동,1317272.800,326481.56,33973.168,144468.30,161.52391,2149.9812,170.74762,...,60.438550,912.473100,208.273510,339.126250,81.739944,49.638496,12.392136,194.319140,785.367600,-0.060108
2,2,2021-07-03,대륜동,1275921.600,327923.47,25219.084,161691.94,200.52660,2358.4468,153.43977,...,59.663357,920.490200,244.384480,326.932000,109.920006,53.871414,13.807532,202.035370,797.542540,-0.221463
3,3,2021-07-04,대륜동,1383577.400,344023.56,23290.570,149400.92,136.67674,2198.2961,172.80410,...,39.266743,889.889040,244.014620,316.016050,111.635440,54.552696,8.977836,216.868100,643.567570,0.371296
4,4,2021-07-05,대륜동,1339020.600,330029.78,37122.465,141534.03,108.46864,1895.7908,176.28185,...,50.170017,911.093500,139.889540,328.539000,57.017544,20.441359,9.824231,169.718960,685.691700,0.543839
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
863,57,2021-08-27,알수없음,15255.924,NaN,NaN,NaN,NaN,NaN,NaN,...,4.955493,74.130325,1.074434,16.943026,11.134865,1.081988,6.511704,22.357502,69.335980,0.097536
864,58,2021-08-28,알수없음,22059.220,NaN,NaN,NaN,NaN,NaN,NaN,...,4.513731,82.080820,6.002088,8.874271,0.720188,1.074199,5.092288,18.096846,62.734543,0.034064
865,59,2021-08-29,알수없음,12094.216,NaN,NaN,NaN,NaN,NaN,NaN,...,7.590064,93.875420,6.753009,4.469733,8.118755,4.330926,-0.272173,0.753010,43.950670,-0.130530
866,60,2021-08-30,알수없음,17867.850,NaN,NaN,NaN,NaN,NaN,NaN,...,1.631795,74.256680,4.132023,3.797277,8.466044,1.396462,2.996644,6.601758,44.034416,-0.003144
867,61,2021-08-31,알수없음,30485.008,NaN,NaN,NaN,NaN,NaN,NaN,...,1.621526,69.948586,4.820905,8.177867,4.928972,2.759588,2.759699,10.921302,55.018597,0.017653

In [11]:
merge3 = merge3.drop(['Unnamed: 0'], axis=1)

In [12]:
merge3

,base_date,emd_nm,em_g,korean_resd_pop_cnt,korean_work_pop_cnt,korean_visit_pop_cnt,longtermfrgn_기타_visit_pop_cnt,longtermfrgn_아시아_visit_pop_cnt,longtermfrgn_기타_resd_pop_cnt,longtermfrgn_아시아_resd_pop_cnt,...,농축수산물_cnt,마트/슈퍼마켓_cnt,배달_cnt,식품_cnt,아시아음식_cnt,양식_cnt,주점및주류판매_cnt,패스트푸드_cnt,한식_cnt,부페_cnt
0,2021-07-01,대륜동,1157136.000,334651.84,30443.098,153682.67,268.03230,2446.2905,145.62045,2357.4014,...,38.646618,762.059100,183.366910,248.291930,54.293083,38.920235,8.797337,166.063020,661.628800,-0.206447
1,2021-07-02,대륜동,1317272.800,326481.56,33973.168,144468.30,161.52391,2149.9812,170.74762,2440.3060,...,60.438550,912.473100,208.273510,339.126250,81.739944,49.638496,12.392136,194.319140,785.367600,-0.060108
2,2021-07-03,대륜동,1275921.600,327923.47,25219.084,161691.94,200.52660,2358.4468,153.43977,2567.7595,...,59.663357,920.490200,244.384480,326.932000,109.920006,53.871414,13.807532,202.035370,797.542540,-0.221463
3,2021-07-04,대륜동,1383577.400,344023.56,23290.570,149400.92,136.67674,2198.2961,172.80410,2624.7070,...,39.266743,889.889040,244.014620,316.016050,111.635440,54.552696,8.977836,216.868100,643.567570,0.371296
4,2021-07-05,대륜동,1339020.600,330029.78,37122.465,141534.03,108.46864,1895.7908,176.28185,2359.4600,...,50.170017,911.093500,139.889540,328.539000,57.017544,20.441359,9.824231,169.718960,685.691700,0.543839
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
863,2021-08-27,알수없음,15255.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.955493,74.130325,1.074434,16.943026,11.134865,1.081988,6.511704,22.357502,69.335980,0.097536
864,2021-08-28,알수없음,22059.220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.513731,82.080820,6.002088,8.874271,0.720188,1.074199,5.092288,18.096846,62.734543,0.034064
865,2021-08-29,알수없음,12094.216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.590064,93.875420,6.753009,4.469733,8.118755,4.330926,-0.272173,0.753010,43.950670,-0.130530
866,2021-08-30,알수없음,17867.850,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.631795,74.256680,4.132023,3.797277,8.466044,1.396462,2.996644,6.601758,44.034416,-0.003144
867,2021-08-31,알수없음,30485.008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.621526,69.948586,4.820905,8.177867,4.928972,2.759588,2.759699,10.921302,55.018597,0.017653

In [13]:
merge = pd.concat((merge1, merge2, merge3), axis = 0)

In [14]:
merge

,base_date,emd_nm,em_g,korean_resd_pop_cnt,korean_work_pop_cnt,korean_visit_pop_cnt,longtermfrgn_기타_visit_pop_cnt,longtermfrgn_아시아_visit_pop_cnt,longtermfrgn_기타_resd_pop_cnt,longtermfrgn_아시아_resd_pop_cnt,...,농축수산물_cnt,마트/슈퍼마켓_cnt,배달_cnt,식품_cnt,아시아음식_cnt,양식_cnt,주점및주류판매_cnt,패스트푸드_cnt,한식_cnt,부페_cnt
0,2021-07-01,아라동,4345753.500,1034529.75,105873.875,279090.78,182.803770,5017.3467,1213.1106,24995.676,...,392.702800,2936.332800,805.672400,717.361000,197.809420,95.010510,56.301266,557.634900,2306.118700,5.164090
1,2021-07-02,아라동,3902727.500,1036852.40,81649.150,276916.00,166.711260,4692.2290,1211.1143,25075.283,...,371.246730,2856.854700,999.765400,752.153900,210.186980,144.916660,49.916030,617.561770,2494.874000,0.688263
2,2021-07-03,아라동,4352217.500,1031199.40,51740.050,249012.55,123.049510,4158.7880,1138.4708,25092.430,...,384.542880,2871.370600,959.425800,791.688800,236.064540,132.605420,59.530014,564.938350,2445.849000,-0.591933
3,2021-07-04,아라동,4399642.000,1061944.80,53604.110,232245.64,83.948494,3776.0117,1111.8708,25392.145,...,289.681000,2551.979500,885.660900,643.069760,173.633270,74.253624,41.481243,474.924070,1936.823400,0.023438
4,2021-07-05,아라동,4547476.000,1026342.70,116858.590,271028.88,132.989180,3706.3580,1250.2146,25964.890,...,300.356230,2454.818400,656.408100,720.976260,130.798190,75.342255,32.881523,354.145750,2216.908400,5.065386
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
863,2021-08-27,알수없음,15255.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.955493,74.130325,1.074434,16.943026,11.134865,1.081988,6.511704,22.357502,69.335980,0.097536
864,2021-08-28,알수없음,22059.220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.513731,82.080820,6.002088,8.874271,0.720188,1.074199,5.092288,18.096846,62.734543,0.034064
865,2021-08-29,알수없음,12094.216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.590064,93.875420,6.753009,4.469733,8.118755,4.330926,-0.272173,0.753010,43.950670,-0.130530
866,2021-08-30,알수없음,17867.850,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.631795,74.256680,4.132023,3.797277,8.466044,1.396462,2.996644,6.601758,44.034416,-0.003144
867,2021-08-31,알수없음,30485.008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.621526,69.948586,4.820905,8.177867,4.928972,2.759588,2.759699,10.921302,55.018597,0.017653

In [15]:
merge['base_date'] = pd.to_datetime(merge['base_date'])

In [16]:
merge['year'] = merge['base_date'].dt.year

In [17]:
merge['month'] = merge['base_date'].dt.month

In [18]:
merge = merge.groupby(['year','month', 'emd_nm'])['em_g'].sum().reset_index()

In [19]:
merge

    year  month emd_nm          em_g
0   2021      7    건입동  3.928077e+07
1   2021      7    구좌읍  2.665902e+07
2   2021      7    남원읍  6.149161e+07
3   2021      7    노형동  2.397688e+08
4   2021      7    대륜동  3.960109e+07
..   ...    ...    ...           ...
79  2021      8    표선면  2.535094e+07
80  2021      8    한경면  2.005269e+07
81  2021      8    한림읍  6.703979e+07
82  2021      8    화북동  1.082289e+08
83  2021      8    효돈동  1.058975e+07

[84 rows x 4 columns]

In [20]:
merge.to_csv("제출용.csv", encoding='utf-8-sig', index=None)